version: '3'
services:

  subsriber_db:
    container_name:  subsriber_db
    image:           postgres
    ports:
      - 5434:5432 # Bind host port 5432 to PostgreSQL port 5432
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - LC_ALL=C.UTF-8

  web:
    build: .
    ports:
      - 8003:5000
    command: flask run -h 0.0.0.0 -p 5000
    volumes:
      - .:/code
    env_file: ./.env
    depends_on:
      - "subsriber_db"

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    command: celery -A subscriber_service.config.celery worker --loglevel=INFO -B
    volumes:
      - .:/code
    env_file: ./.env
    depends_on:
      - "subsriber_db"


networks:
  default:
    external:
      name: redis
