version: '3'
services:

  subsriber_db:
    container_name:  subsriber_db
    image:           postgres
    ports:
      - 5434:5432 # Bind host port 5432 to PostgreSQL port 5432
    restart: always
    volumes:
      - ../db-data:/var/lib/postgresql/data
    env_file: ../.env
    environment:
      - LC_ALL=C.UTF-8
