version: '3.1'

services: 
    redisdb:
        image: redis
        ports: 
            - "6380:6379"
        volumes:
            - ./redisdb:/data
    
    web:
        build: .
        command: flask run --host 0.0.0.0 -p 5000
        ports: 
            - "8000:5000"
        depends_on: 
            - "redisdb"
        environment: 
            - FLASK_APP=main.py
            - DEBUG=idris

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
        - REDIS_HOSTS=local:redisdb:6379
        ports:
        - "8081:8081"
