# Generated by Django 2.2.8 on 2021-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.CharField(default='slug', max_length=140, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.CharField(default='slug', max_length=140, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
