# Generated by Django 2.2.8 on 2021-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210706_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug_az',
            field=models.CharField(max_length=140, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='story',
            name='slug_en',
            field=models.CharField(max_length=140, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='story',
            name='slug_ru',
            field=models.CharField(max_length=140, null=True, verbose_name='Slug'),
        ),
    ]
