# Generated by Django 2.2.8 on 2021-06-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210610_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.RecipeComment'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.StoryComment'),
        ),
    ]
