# Generated by Django 2.2.8 on 2021-07-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20210706_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.CharField(editable=False, max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug_az',
            field=models.CharField(editable=False, max_length=140, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug_en',
            field=models.CharField(editable=False, max_length=140, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug_ru',
            field=models.CharField(editable=False, max_length=140, null=True, verbose_name='Slug'),
        ),
    ]
