# Generated by Django 2.2.8 on 2021-06-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20210610_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ad soyad')),
                ('image', models.ImageField(upload_to='media/authors', verbose_name='foto')),
                ('gender', models.BinaryField(verbose_name='cins')),
                ('date_of_birthday', models.DateTimeField(verbose_name='dogum tarixi')),
                ('nationality', models.CharField(max_length=255, verbose_name='milliyet')),
                ('info', models.TextField(verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('title',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Basliq')),
                ('description', models.TextField(verbose_name='Haqqinda')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='qiymet')),
                ('page_count', models.IntegerField(verbose_name='sehife sayi')),
                ('cover_image', models.ImageField(upload_to='media/book_covers', verbose_name='uz qabigi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='stories.Author')),
                ('categories', models.ManyToManyField(related_name='books', to='stories.Category')),
            ],
        ),
    ]
