# Generated by Django 2.2.8 on 2021-06-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20210615_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birthday',
        ),
        migrations.RemoveField(
            model_name='author',
            name='gender',
        ),
    ]
